// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelApi.Services.DataSource;

#nullable disable

namespace ModelApi.Migrations
{
    [DbContext(typeof(SelfFinanceDbContext))]
    partial class SelfFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelApi.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("TYPE_EXPENSE_ID");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("EXPENSES", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ModelApi.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("TYPE_INCOME_ID");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("INCOMES", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ModelApi.Entities.TypeExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TYPES_EXPENSES", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ModelApi.Entities.TypeIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TYPES_INCOMES", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ModelApi.Entities.Expense", b =>
                {
                    b.HasOne("ModelApi.Entities.TypeExpense", "TypeExpense")
                        .WithMany("Expenses")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ModelApi.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("money")
                                .HasColumnName("AMOUNT");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.FreeText", "Comments", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("COMMENTS");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "CreateDate", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("CREATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "UpdateDate", b1 =>
                        {
                            b1.Property<int>("ExpenseId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("UPDATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("CreateDate")
                        .IsRequired();

                    b.Navigation("TypeExpense");

                    b.Navigation("UpdateDate");
                });

            modelBuilder.Entity("ModelApi.Entities.Income", b =>
                {
                    b.HasOne("ModelApi.Entities.TypeIncome", "TypeIncome")
                        .WithMany("Incomes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ModelApi.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("IncomeId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("money")
                                .HasColumnName("AMOUNT");

                            b1.HasKey("IncomeId");

                            b1.ToTable("INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.FreeText", "Comments", b1 =>
                        {
                            b1.Property<int>("IncomeId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("COMMENTS");

                            b1.HasKey("IncomeId");

                            b1.ToTable("INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "CreateDate", b1 =>
                        {
                            b1.Property<int>("IncomeId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("CREATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("IncomeId");

                            b1.ToTable("INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "UpdateDate", b1 =>
                        {
                            b1.Property<int>("IncomeId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("UPDATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("IncomeId");

                            b1.ToTable("INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("IncomeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("CreateDate")
                        .IsRequired();

                    b.Navigation("TypeIncome");

                    b.Navigation("UpdateDate");
                });

            modelBuilder.Entity("ModelApi.Entities.TypeExpense", b =>
                {
                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "CreateDate", b1 =>
                        {
                            b1.Property<int>("TypeExpenseId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("CREATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("TypeExpenseId");

                            b1.ToTable("TYPES_EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("TypeExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.FreeText", "Description", b1 =>
                        {
                            b1.Property<int>("TypeExpenseId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DESCRIPTION");

                            b1.HasKey("TypeExpenseId");

                            b1.ToTable("TYPES_EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("TypeExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("TypeExpenseId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NAME");

                            b1.HasKey("TypeExpenseId");

                            b1.ToTable("TYPES_EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("TypeExpenseId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "UpdateDate", b1 =>
                        {
                            b1.Property<int>("TypeExpenseId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("UPDATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("TypeExpenseId");

                            b1.ToTable("TYPES_EXPENSES");

                            b1.WithOwner()
                                .HasForeignKey("TypeExpenseId");
                        });

                    b.Navigation("CreateDate")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("UpdateDate");
                });

            modelBuilder.Entity("ModelApi.Entities.TypeIncome", b =>
                {
                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "CreateDate", b1 =>
                        {
                            b1.Property<int>("TypeIncomeId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("CREATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("TypeIncomeId");

                            b1.ToTable("TYPES_INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("TypeIncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.FreeText", "Description", b1 =>
                        {
                            b1.Property<int>("TypeIncomeId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DESCRIPTION");

                            b1.HasKey("TypeIncomeId");

                            b1.ToTable("TYPES_INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("TypeIncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("TypeIncomeId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("NAME");

                            b1.HasKey("TypeIncomeId");

                            b1.ToTable("TYPES_INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("TypeIncomeId");
                        });

                    b.OwnsOne("ModelApi.ValueObjects.DateOperation", "UpdateDate", b1 =>
                        {
                            b1.Property<int>("TypeIncomeId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetime")
                                .HasColumnName("UPDATE_DATE")
                                .HasDefaultValueSql("GETDATE()");

                            b1.HasKey("TypeIncomeId");

                            b1.ToTable("TYPES_INCOMES");

                            b1.WithOwner()
                                .HasForeignKey("TypeIncomeId");
                        });

                    b.Navigation("CreateDate")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("UpdateDate");
                });

            modelBuilder.Entity("ModelApi.Entities.TypeExpense", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("ModelApi.Entities.TypeIncome", b =>
                {
                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
